# Generated by Django 5.2.5 on 2025-08-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userintake_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="weight",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userintake",
            name="target_calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userintake",
            name="target_carbohydrates",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userintake",
            name="target_fats",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userintake",
            name="target_proteins",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
